WITH CP1 AS (SELECT DISTINCT cp.CART_ID, cp.NAME
FROM CART_PRODUCTS cp
WHERE cp.NAME = 'Milk' OR cp.NAME = 'Yogurt')

SELECT CP1.CART_ID
FROM CP1
GROUP BY CP1.CART_ID
HAVING COUNT(*) = 2
ORDER BY CP1.CART_ID ASC