SELECT ED1.ID,
CASE
WHEN ED2.PER <= 0.25 THEN 'CRITICAL'
WHEN ED2.PER <= 0.5 THEN 'HIGH'
WHEN ED2.PER <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA ED1
LEFT JOIN (SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA) AS ED2 ON ED1.ID = ED2.ID
ORDER BY ED1.ID ASC
