WITH RECURSIVE VAR AS (
SELECT ED1.ID AS ID, ED1.PARENT_ID AS PARENT_ID, 1 AS GENERATION
FROM ECOLI_DATA ED1
WHERE ED1.PARENT_ID IS NULL
    
UNION ALL

SELECT ED2.ID, ED2.PARENT_ID, VAR.GENERATION + 1 AS GENERATION
FROM VAR
JOIN ECOLI_DATA ED2 ON VAR.ID = ED2.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM VAR
WHERE ID NOT IN (
SELECT DISTINCT parent_id
FROM VAR
WHERE parent_id IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION