WITH var AS (
SELECT CAR.DAILY_FEE, CAR.CAR_TYPE, HISTORY.HISTORY_ID,
    DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 AS PERIOD,
    CASE
    WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON HISTORY.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_TYPE = '트럭'
)

select v.HISTORY_ID, ROUND(v.PERIOD * v.DAILY_FEE * (100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100) AS FEE
from var v
left join CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON v.DURATION_TYPE = PLAN.DURATION_TYPE
AND v.CAR_TYPE = PLAN.CAR_TYPE
order by FEE DESC, v.HISTORY_ID DESC