WITH VAR_GRADE AS (
SELECT EMP_NO, AVG(SCORE),
CASE
WHEN AVG(SCORE) >= 96 THEN 20
WHEN AVG(SCORE) >= 90 THEN 15
WHEN AVG(SCORE) >= 80 THEN 10
ELSE 0
END AS SURPLUS,
CASE
WHEN AVG(SCORE) >= 96 THEN 'S'
WHEN AVG(SCORE) >= 90 THEN 'A'
WHEN AVG(SCORE) >= 80 THEN 'B'
ELSE 'C'
END AS RESULT_GRADE
FROM HR_GRADE
GROUP BY EMP_NO
)

# SELECT EMP_NO, MAX(YEAR), AVG(SCORE), MIN(SURPLUS), MAX(RESULT_GRADE)
# FROM VAR_GRADE GRADE
# GROUP BY EMP_NO

# SELECT *
# FROM VAR_GRADE

SELECT EMP.EMP_NO, MAX(EMP.EMP_NAME) AS EMP_NAME, MAX(VAR_GRADE.RESULT_GRADE) AS GRADE, MIN((VAR_GRADE.SURPLUS * 0.01) * EMP.SAL) AS BONUS
FROM HR_EMPLOYEES EMP
JOIN (
SELECT *
FROM VAR_GRADE GRADE
GROUP BY EMP_NO
) AS VAR_GRADE ON EMP.EMP_NO = VAR_GRADE.EMP_NO
GROUP BY EMP_NO
ORDER BY EMP.EMP_NO ASC